apiVersion: v1
kind: ConfigMap
metadata:
  name: verne-conf
  namespace: verne
data:
  # verne container 
  DOCKER_VERNEMQ_ACCEPT_EULA: "yes"
  DOCKER_VERNEMQ_ALLOW_ANONYMOUS: "on" 
  # listener container
  HOST_PATH: "/envs/host_ip"
  MQTT_PORT: "1883"
  MQTT_CONNECT_SUCCESS_PATH: "/tmp/listener.status"
  PUBSUB_CONNECT_SUCCESS_PATH: "/tmp/pub.status"
  MQTT_TOPIC:
  