#service for verneMQ pods
apiVersion: v1
kind: Service
metadata:
  name: vernemq-broker
  namespace: verne
spec:
  selector:
    app: broker
  ports:
  - name: mqtt
    port: 1883
    targetPort: 1883
  - name: metrics
    port: 8888
    targetPort: 8888
