#Roles for the pods
#[context: verneMQ setups up clustering with other pods via k8s API, so give that access to make calls]

apiVersion: v1
kind: ServiceAccount
metadata:
  name: vernemq
  namespace: verne

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vernemq-role
  namespace: verne
rules:
- apiGroups: [""]
  resources: ["pods", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get", "list", "watch"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vernemq-rolebinding
  namespace: verne
subjects:
- kind: ServiceAccount
  name: vernemq
  namespace: verne
roleRef:
  kind: Role
  name: vernemq-role
  apiGroup: rbac.authorization.k8s.io