version: '3'

dotenv: ['.tf.env']


tasks:
  get-config:
    desc: get variables for terraform
    cmds:
      - cat .tf.env 

  init:
    desc: initialize terraform providers
    cmds: 
      - terraform init 

  plan:
    cmds:
      - terraform plan

  validate:
    cmds:
      - terraform validate

  apply:
    cmds:
      - terraform apply

  apply-debug:
    desc: apply TF changes in debug mode
    cmds:
      - TF_LOG=DEBUG terraform apply -auto-approve 2>&1 | tee tf_debug.log

  list:
    cmds:
      - terraform state list

  destroy-all:
    cmds:
      - terraform destroy

  destroy-single:
    cmds:
      - terraform destroy -target={{.CLI_ARGS}}
