additionalPodMonitors:
  - name: vernemq
    selector:
      matchLabels:
        app: broker
    namespaceSelector:
      matchNames:   
        - mqtt 
    podMetricsEndpoints:
      - port: metrics
        path: /metrics
