image:
  repository: grafana/grafana
  tag: latest
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      url: http://loki-gateway.observe.svc.cluster.local
      access: proxy
      isDefault: false
      editable: true
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server.observe.svc.cluster.local
      access: proxy
      isDefault: true
      editable: true

service:
  type: NodePort
  port: 3045