version: '3'

env:
  VERNE_NAMESPACE: verne
  MONITOR_NAMESPACE: monitor

tasks:
  ns-create:
    desc: create all required namespaces
    cmds:
      - pwd
      - kubectl apply -f ./k8s/namespaces/

  monitor-destroy:
    desc: helm upgrade the prom-operator pods (afterany config changes)
    cmds: 
      - >
        helm upgrade --install kube-prometheus-stack 
        prometheus-community/kube-prometheus-stack 
        --namespace $MONITOR_NAMESPACE 
        --values ./k8s/monitor/prometheus-operator.yaml

  monitor-deploy:
    desc: helm destroy the monitoring stack
    cmds:
      - helm uninstall kube-prometheus-stack --namespace $MONITOR_NAMESPACE

  grafana-expose:
    desc: export grafana on port 3000 to monitor the k8s pods & metrics
    cmds:
      - |
        export POD_NAME=$(kubectl --namespace $MONITOR_NAMESPACE get pod -l "app.kubernetes.io/name=grafana,app.kubernetes.io/instance=kube-prometheus-stack" -oname)
        kubectl --namespace $MONITOR_NAMESPACE port-forward $POD_NAME 3000 

  verne-deploy:
    desc: deploy verneMQTT cluster
    deps: [ns-create]
    cmds: 
      - kubectl apply -f ./k8s/vernemq/verne-roles.yaml
      - kubectl apply -f ./k8s/vernemq/verne-depl.yaml
      - kubectl apply -f ./k8s/vernemq/verne-service.yaml

  verne-destroy:
    desc: destroy the verneMQTT & related pods
    cmds: 
      - kubectl delete namespace verne

  locust-build:
    dir: ./source/locust/
    desc: rebuild the locust source image from Dockerfile
    cmds:
      - docker build -t locust-loader:latest .

  listener-build:
    dir: ./source/listener
    desc: rebuild the listener source image from Dockerfile
    cmds:
      - docker build --no-cache -t verne-listener:v1 .

  listener-push:
    desc: push the listener image to dockerhub
    cmds: 
      - docker tag verne-listener:v1 sardinesszsz/verne-listener:v1
      - docker push sardinesszsz/verne-listener:v1 

  load-test:
    dir: ./source/locust/
    desc: run locust web ui locally to start load testing
    cmds:
      - zsh -i -c "conda activate logcore && locust"
 
 
  
  